language: bash

services: docker

env:
  - VERSION=7.0

before_script:
  - env | sort
  - cd "${VERSION}"
  - IMAGE="schroedan/php:${VERSION}"

script:
  - travis_retry docker build -t "$IMAGE" .

after_script:
  - docker images
