language: bash

services: docker

env:
  - VERSION=5.6
  - VERSION=7.0
  - VERSION=7.1
  - VERSION=7.2
  - VERSION=7.3

before_script:
  - env | sort
  - cd "${VERSION}"
  - IMAGE="schroedan/php:${VERSION}"

script:
  - travis_retry docker build -t "$IMAGE" .

after_script:
  - docker images
